name: Some Workflow

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  persist-artifact:
    name: Persist Artifact
    if: ${{ github.event_name == 'push' }} # we are filtered ☝️ so this is a commit to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{github.run_id}}" > artifact
      - uses: actions/upload-artifact@v2
        with:
          name: artifact-${{github.sha}}
          path: artifact
  compare-artifacts:
    name: Compare Artifacts
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact from base ref ${{github.event.pull_request.head.ref}}
        uses: actions/download-artifact@v2
        with:
          name: artifact-${{github.event.pull_request.head.ref}}
      - run: |
          ls -la
          echo "${{github.run_id}}" > new_artifact
          echo "new artifact:"
          cat ./new_artifact
          echo "downloaded artifact:"
          cat ./artifact


